'use strict';
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {SlashCommandBuilder,PermissionFlagsBits,EmbedBuilder,ChannelType}=require('discord.js');
const BASE='https://api.twitch.tv/helix';
const clean=(s,n=1000)=>String(s??'').replace(/@everyone|@here/gi,m=>'@\u200b'+m.slice(1)).slice(0,n);
const safeName=s=>String(s??'').replace(/[\u0000-\u001f<>]/g,'').slice(0,60);
function duration(s){const m=/^(\d+)([mhd])$/i.exec(String(s||''));if(!m)return 0;const n=Number(m[1])*({m:60000,h:3600000,d:86400000})[m[2].toLowerCase()];return n>=60000&&n<=2592000000?n:0;}
function draw(ids,n){const a=[...new Set(ids)];for(let i=0;i<Math.min(n,a.length);i++){const j=i+crypto.randomInt(a.length-i);[a[i],a[j]]=[a[j],a[i]];}return a.slice(0,n);}
const commands=[new SlashCommandBuilder().setName('streamgiveaway').setDescription('Twitch-Stream-Gewinnspiele verwalten').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('start').setDescription('Gewinnspiel im Twitch-Chat starten').addStringOption(o=>o.setName('preis').setDescription('Gewinn').setRequired(true).setMaxLength(150)).addStringOption(o=>o.setName('dauer').setDescription('10m, 2h oder 1d').setRequired(true)).addIntegerOption(o=>o.setName('gewinner').setDescription('Anzahl').setMinValue(1).setMaxValue(20)).addStringOption(o=>o.setName('keyword').setDescription('Teilnahme, z.B. !join').setMaxLength(30)))
.addSubcommand(s=>s.setName('status').setDescription('Gewinnspielstatus anzeigen'))
.addSubcommand(s=>s.setName('end').setDescription('Jetzt auslosen'))
.addSubcommand(s=>s.setName('reroll').setDescription('Neue Gewinner ohne vorherige Gewinner').addIntegerOption(o=>o.setName('gewinner').setDescription('Anzahl').setMinValue(1).setMaxValue(20)))
.addSubcommand(s=>s.setName('cancel').setDescription('Gewinnspiel abbrechen'))
.addSubcommand(s=>s.setName('overlay').setDescription('Private OBS-Overlay-URL anzeigen')),
new SlashCommandBuilder().setName('stream').setDescription('Twitch-Stream und Discord-Ankündigung').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('setup').setDescription('Ankündigung und Text konfigurieren').addChannelOption(o=>o.setName('channel').setDescription('Ankündigungskanal').setRequired(true).addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement)).addStringOption(o=>o.setName('text').setDescription('Eigener Text; {title}, {game}, {url}').setMaxLength(1500)).addRoleOption(o=>o.setName('rolle').setDescription('Optionale Pingrolle')))
.addSubcommand(s=>s.setName('status').setDescription('Twitch-Verbindung und Einstellungen'))
.addSubcommand(s=>s.setName('connect').setDescription('Privaten Twitch-Freigabelink erzeugen'))
.addSubcommand(s=>s.setName('test').setDescription('Testankündigung ohne Ping'))
.addSubcommand(s=>s.setName('live').setDescription('Twitch-Livestatus sofort prüfen'))
.addSubcommand(s=>s.setName('enable').setDescription('Live-Ankündigungen aktivieren'))
.addSubcommand(s=>s.setName('disable').setDescription('Live-Ankündigungen deaktivieren'))];
class StreamIntegration{
 constructor({client,env=process.env,fetchFn=fetch,WebSocketClass=globalThis.WebSocket,now=Date.now,random=crypto.randomBytes,logger=console}={}){
  this.client=client;this.env=env;this.fetch=fetchFn;this.WS=WebSocketClass;this.now=now;this.random=random;this.log=logger;
  this.channel=(env.TWITCH_CHANNEL||'toomturboo').toLowerCase().replace(/^https?:\/\/.*?twitch\.tv\//,'').replace(/\/$/,'');if(!/^[a-z0-9_]{4,25}$/.test(this.channel))throw new Error('Ungültiger Twitch-Kanal.');
  this.id=env.TWITCH_CLIENT_ID||'';this.secret=env.TWITCH_CLIENT_SECRET||'';this.publicUrl=(env.PUBLIC_URL||'').replace(/\/$/,'');
  this.guildId=env.STREAM_GUILD_ID||env.DISCORD_GUILD_ID||'';this.ownerIds=new Set((env.MASTER_USER_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
  const dir=env.RAILWAY_VOLUME_MOUNT_PATH||env.DATA_DIR||path.join(process.cwd(),'data');fs.mkdirSync(dir,{recursive:true});
  this.db=new DatabaseSync(path.join(dir,'unfug-stream.sqlite'));this.db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS kv(k TEXT PRIMARY KEY,v TEXT NOT NULL); CREATE TABLE IF NOT EXISTS entries(gid TEXT NOT NULL,uid TEXT NOT NULL,name TEXT NOT NULL,PRIMARY KEY(gid,uid)); CREATE TABLE IF NOT EXISTS seen(id TEXT PRIMARY KEY,at INTEGER NOT NULL);');
  this.state=this.get('state',{});this.auth=this.get('auth',{});this.overlayKey=this.get('overlayKey',null)||random(32).toString('hex');this.put('overlayKey',this.overlayKey);
  this.pending=new Map();this.appToken=null;this.appExpires=0;this.refreshPromise=null;this.ws=null;this.reconnectTimer=null;this.sessionId=null;this.started=false;this.polling=false;this.drawing=false;this.seenMessages=new Set();this.lastChatAt=0;this.lastEventAt=0;this.keepaliveMs=30000;this.ready=false;this.lastError='';
 }
 get(k,d){const r=this.db.prepare('SELECT v FROM kv WHERE k=?').get(k);return r?JSON.parse(r.v):d;}
 put(k,v){this.db.prepare('INSERT INTO kv(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').run(k,JSON.stringify(v));}
 save(){this.put('state',this.state);}
 config(){return this.state.config||{};}
 authorized(i){return !!i.inGuild?.()&&i.guildId===this.guildId&&(i.guild?.ownerId===i.user.id||this.ownerIds.has(i.user.id)||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild));}
 async request(url,opts={}){const r=await this.fetch(url,{...opts,signal:AbortSignal.timeout(15000)});const text=await r.text();let j;try{j=JSON.parse(text);}catch{j={message:text};}if(!r.ok)throw new Error('Twitch HTTP '+r.status+': '+clean(j.message||'API-Fehler',180));return j;}
 async tokenRequest(params){return this.request('https://id.twitch.tv/oauth2/token',{method:'POST',body:new URLSearchParams({client_id:this.id,client_secret:this.secret,...params})});}
 async appAuth(){if(this.appToken&&this.appExpires>this.now()+60000)return this.appToken;const j=await this.tokenRequest({grant_type:'client_credentials'});this.appToken=j.access_token;this.appExpires=this.now()+j.expires_in*1000;return this.appToken;}
 async userAuth(){if(!this.auth.access_token)throw new Error('Twitch noch nicht freigegeben. /stream connect verwenden.');if(this.auth.expiresAt>this.now()+120000)return this.auth.access_token;if(this.refreshPromise)return this.refreshPromise;this.refreshPromise=(async()=>{const j=await this.tokenRequest({grant_type:'refresh_token',refresh_token:this.auth.refresh_token});this.auth={...this.auth,...j,expiresAt:this.now()+j.expires_in*1000};this.put('auth',this.auth);return this.auth.access_token;})();try{return await this.refreshPromise;}finally{this.refreshPromise=null;}}
 async helix(route,{user=false,method='GET',body,retry=true}={}){const token=user?await this.userAuth():await this.appAuth();const r=await this.fetch(BASE+route,{method,headers:{'Client-ID':this.id,Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(r.status===401&&retry){if(user){this.auth.expiresAt=0;this.put('auth',this.auth);}else this.appToken=null;return this.helix(route,{user,method,body,retry:false});}const text=await r.text();let j;try{j=JSON.parse(text);}catch{j={};}if(!r.ok)throw new Error('Twitch HTTP '+r.status+': '+clean(j.message||'API-Fehler',160));return j;}
 async resolveChannel(){if(this.channelId)return this.channelId;const j=await this.helix('/users?login='+encodeURIComponent(this.channel));const u=j.data?.[0];if(!u)throw new Error('Twitch-Kanal nicht gefunden');this.channelId=u.id;return u.id;}
 async validateAuth(){if(!this.auth.access_token)return false;const token=await this.userAuth();let j;try{j=await this.request('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:'OAuth '+token}});}catch(e){if(!String(e.message).includes('HTTP 401'))throw e;this.auth.expiresAt=0;this.put('auth',this.auth);const renewed=await this.userAuth();j=await this.request('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:'OAuth '+renewed}});}if(!j.scopes?.includes('user:read:chat'))throw new Error('Twitch-Chat-Leserecht fehlt');this.auth.userId=j.user_id;this.put('auth',this.auth);return true;}
 async connectUrl(userId){if(!this.id||!this.secret||!this.publicUrl)throw new Error('TWITCH_CLIENT_ID, TWITCH_CLIENT_SECRET und PUBLIC_URL fehlen.');const state=this.random(32).toString('hex');this.pending.set(state,{userId,expires:this.now()+600000});const q=new URLSearchParams({client_id:this.id,redirect_uri:this.publicUrl+'/stream/oauth/callback',response_type:'code',scope:'user:read:chat user:write:chat',state});return 'https://id.twitch.tv/oauth2/authorize?'+q;}
 async callback(req,res,u){const pending=this.pending.get(u.searchParams.get('state'));this.pending.delete(u.searchParams.get('state'));if(!pending||pending.expires<this.now()||!u.searchParams.get('code'))return this.respond(res,400,'Freigabe abgelaufen oder abgelehnt. /stream connect erneut ausführen.');try{const j=await this.tokenRequest({grant_type:'authorization_code',code:u.searchParams.get('code'),redirect_uri:this.publicUrl+'/stream/oauth/callback'});const previous=this.auth;this.auth={...j,expiresAt:this.now()+j.expires_in*1000};this.put('auth',this.auth);await this.validateAuth();const cid=await this.resolveChannel();if(this.auth.userId!==cid){this.auth=previous;this.put('auth',this.auth);throw new Error('Bitte den Twitch-Kanal '+this.channel+' freigeben.');}this.ready=true;this.openChat();return this.respond(res,200,'Twitch verbunden. Du kannst dieses Fenster schließen.');}catch(e){this.auth={};this.put('auth',this.auth);return this.respond(res,400,'Twitch-Verbindung fehlgeschlagen. Prüfe Railway-Logs und versuche es erneut.');}}
 respond(res,status,text){res.writeHead(status,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end(text);}
 async sendChat(message){const cid=await this.resolveChannel();return this.helix('/chat/messages',{user:true,method:'POST',body:{broadcaster_id:cid,sender_id:this.auth.userId,message:clean(message,450)}});}
 async subscribe(sessionId){const cid=await this.resolveChannel();await this.helix('/eventsub/subscriptions',{user:true,method:'POST',body:{type:'channel.chat.message',version:'1',condition:{broadcaster_user_id:cid,user_id:this.auth.userId},transport:{method:'websocket',session_id:sessionId}}});}
 openChat(url='wss://eventsub.wss.twitch.tv/ws'){if(!this.auth.access_token||!this.WS)return;if(this.ws){try{this.ws.close();}catch{}}const ws=new this.WS(url);this.ws=ws;ws.addEventListener('message',ev=>{this.onEvent(JSON.parse(ev.data)).catch(e=>this.error(e));});ws.addEventListener('close',()=>{if(this.ws!==ws||!this.started)return;this.sessionId=null;clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(()=>this.openChat(),5000);this.reconnectTimer.unref?.();});ws.addEventListener('error',()=>{});}
 async onEvent(m){this.lastEventAt=this.now();const t=m.metadata?.message_type;if(t==='session_welcome'){this.sessionId=m.payload.session.id;this.keepaliveMs=Math.max(10000,Number(m.payload.session.keepalive_timeout_seconds||30)*1000);await this.subscribe(this.sessionId);}else if(t==='session_reconnect'){this.openChat(m.payload.session.reconnect_url);}else if(t==='notification'&&m.metadata.subscription_type==='channel.chat.message'){const e=m.payload.event;this.lastChatAt=this.now();this.join(e);} }
 join(e){const g=this.state.giveaway;if(!g||g.status!=='active'||g.endsAt<=this.now()||e.chatter_is_anonymous||!e.chatter_user_id||e.chatter_user_id===this.channelId)return false;if(!e.message?.text||e.message.text.trim().toLowerCase()!==g.keyword)return false;const id=e.message_id;if(id&&this.seenMessages.has(id))return false;if(id){this.seenMessages.add(id);if(this.seenMessages.size>2000)this.seenMessages.clear();}this.db.prepare('INSERT OR IGNORE INTO entries(gid,uid,name) VALUES(?,?,?)').run(g.id,e.chatter_user_id,safeName(e.chatter_user_name||e.chatter_user_login));return true;}
 entries(g){return this.db.prepare('SELECT uid,name FROM entries WHERE gid=? ORDER BY uid').all(g.id);}
 count(g){return this.db.prepare('SELECT COUNT(*) n FROM entries WHERE gid=?').get(g.id).n;}
 startGiveaway({prize,ms,winners=1,keyword='!join'}){const old=this.state.giveaway;if(old?.status==='active'||old?.status==='drawing'||old?.pending)throw new Error('Das vorherige Giveaway oder seine Ergebnisveröffentlichung ist noch nicht abgeschlossen.');if(!String(prize||'').trim()||!ms||!Number.isInteger(winners)||winners<1||winners>20||!/^![a-z0-9_-]{1,29}$/i.test(keyword))throw new Error('Ungültige Dauer, Gewinnerzahl oder Keyword.');const g={id:this.random(12).toString('hex'),prize:clean(prize,150),status:'active',createdAt:this.now(),endsAt:this.now()+ms,winners,keyword:keyword.toLowerCase(),winnerIds:[],history:[],pending:null};this.state.giveaway=g;this.save();return g;}
 async endGiveaway(){if(this.drawing)throw new Error('Auslosung läuft bereits.');this.drawing=true;try{const g=this.state.giveaway;if(!g||!['active','drawing'].includes(g.status))throw new Error('Kein laufendes Giveaway.');g.status='drawing';this.save();const entries=this.entries(g);const ids=draw(entries.map(e=>e.uid),g.winners);const names=ids.map(id=>entries.find(e=>e.uid===id).name);g.winnerIds=ids;g.history.push({at:this.now(),ids,names});g.status='ended';g.endedAt=this.now();g.displayAt=this.now();g.pending={id:this.random(12).toString('hex'),text:ids.length?'Gewinner: '+names.join(', '):'Keine gültigen Teilnehmer.'};this.save();await this.publishResult();return g;}finally{this.drawing=false;}}
 async reroll(n){if(this.drawing)throw new Error('Auslosung läuft.');this.drawing=true;try{const g=this.state.giveaway;if(!g||g.status!=='ended')throw new Error('Kein beendetes Giveaway.');if(g.pending)throw new Error('Das vorherige Ergebnis wird noch veröffentlicht.');const excluded=new Set(g.history.flatMap(h=>h.ids));const entries=this.entries(g).filter(e=>!excluded.has(e.uid));const ids=draw(entries.map(e=>e.uid),n||g.winners);const names=ids.map(id=>entries.find(e=>e.uid===id).name);g.winnerIds=ids;g.history.push({at:this.now(),ids,names});g.displayAt=this.now();g.pending={id:this.random(12).toString('hex'),text:ids.length?'Neuziehung: '+names.join(', '):'Keine weiteren Teilnehmer verfügbar.'};this.save();await this.publishResult();return g;}finally{this.drawing=false;}}
 async publishResult(){if(this.publishing)return;this.publishing=true;try{const g=this.state.giveaway;if(!g?.pending||!this.auth.access_token)return;const id=g.pending.id;await this.sendChat(g.pending.text);if(g.pending?.id===id){g.pending=null;this.save();}}finally{this.publishing=false;}}
 async poll(){if(this.polling||!this.id||!this.secret)return;this.polling=true;try{const s=(await this.helix('/streams?user_login='+encodeURIComponent(this.channel))).data?.[0]||null;this.state.live=s?{id:s.id,title:s.title,game:s.game_name,startedAt:s.started_at}:null;this.save();if(s)await this.announce(s);const g=this.state.giveaway;if(g?.status==='active'&&g.endsAt<=this.now())await this.endGiveaway();if(g?.pending)await this.publishResult();this.lastError='';}catch(e){this.error(e);}finally{this.polling=false;}}
 async announce(s,{test=false}={}){const c=this.config();if(!c.channelId||(!c.enabled&&!test)||(!test&&this.state.announcedId===s.id))return;const ch=await this.client.channels.fetch(c.channelId);if(!ch?.isTextBased())throw new Error('Ankündigungskanal nicht erreichbar');const url='https://www.twitch.tv/'+this.channel;const text=(c.text||'🔴 **UNFUG ist live!**\n{title}\n{url}').replace(/\{title\}/g,clean(s.title,240)).replace(/\{game\}/g,clean(s.game_name,120)).replace(/\{url\}/g,url);const role=!test&&c.roleId?'<@&'+c.roleId+'>\n':'';if(!test){try{const recent=await ch.messages.fetch({limit:30});const found=recent.find(m=>m.author?.id===this.client.user.id&&m.embeds?.some(e=>e.footer?.text==='UNFUG • STREAM SESSION '+s.id));if(found){this.state.announcedId=s.id;this.state.announceMessageId=found.id;this.save();return;}}catch{}}const embed=new EmbedBuilder().setColor(0x8b5cf6).setTitle(test?'TEST • Twitch-Ankündigung':'🔴 UNFUG IST LIVE').setDescription(clean(text,3500)).setURL(url).setFooter({text:'UNFUG • STREAM SESSION '+s.id}).setTimestamp();if(!test){this.state.announcedId=s.id;this.save();}try{const m=await ch.send({content:role,embeds:[embed],nonce:crypto.createHash('sha256').update('unfug-stream:'+s.id+':'+ch.id).digest('hex').slice(0,24),enforceNonce:true,allowedMentions:{parse:[],roles:role?[c.roleId]:[]}});if(!test){this.state.announceMessageId=m.id;this.save();}}catch(e){if(!test){this.state.announcedId=null;this.save();}throw e;}}
 async handle(i){if(!i.isChatInputCommand?.()||!['stream','streamgiveaway'].includes(i.commandName))return false;if(!this.authorized(i)){await i.reply({content:'Keine Berechtigung oder falscher Server.',ephemeral:true});return true;}await i.deferReply({ephemeral:true});try{const sub=i.options.getSubcommand();let text='';if(i.commandName==='stream'){
 if(sub==='connect'){text='Öffne diesen privaten Link und melde dich mit deinem Twitch-Konto an:\n'+await this.connectUrl(i.user.id);}
 else if(sub==='setup'){const c=this.config();c.channelId=i.options.getChannel('channel').id;c.text=i.options.getString('text')||c.text||'🔴 **UNFUG ist live!**\n{title}\n{url}';c.roleId=i.options.getRole('rolle')?.id||null;c.enabled=true;this.state.config=c;this.save();text='Ankündigung eingerichtet. Text und Pingrolle gespeichert.';}
 else if(sub==='enable'||sub==='disable'){this.state.config={...this.config(),enabled:sub==='enable'};this.save();text='Live-Ankündigungen '+(sub==='enable'?'aktiviert.':'deaktiviert.');}
 else if(sub==='status'){text=JSON.stringify({channel:this.channel,twitchConnected:!!this.auth.access_token,chatSession:!!this.sessionId,announceEnabled:!!this.config().enabled,announceChannel:this.config().channelId||null,lastError:this.lastError},null,2);}
 else if(sub==='test'){await this.announce({id:'test',title:'Teststream',game_name:'FiveM'},{test:true});text='Testnachricht ohne Ping gesendet.';}
 else if(sub==='live'){await this.poll();text=this.state.live?'Twitch ist live: '+clean(this.state.live.title,180):'Twitch ist derzeit offline.';}
 }else{
 if(sub==='start'){if(!this.auth.access_token||!this.sessionId)throw new Error('Twitch-Chat noch nicht verbunden. /stream connect verwenden.');const g=this.startGiveaway({prize:i.options.getString('preis'),ms:duration(i.options.getString('dauer')),winners:i.options.getInteger('gewinner')||1,keyword:i.options.getString('keyword')||'!join'});await this.sendChat('🎁 Giveaway: '+g.prize+' | Teilnahme: '+g.keyword+' | Dauer: '+i.options.getString('dauer'));text='Giveaway gestartet. ID: '+g.id;}
 else if(sub==='status'){const g=this.state.giveaway;text=g?JSON.stringify({prize:g.prize,status:g.status,participants:this.count(g),endsAt:new Date(g.endsAt).toISOString(),winners:g.history.at(-1)?.names||[]},null,2):'Noch kein Giveaway.';}
 else if(sub==='end'){const g=await this.endGiveaway();text=g.pending?'Ausgelost. Chat-Nachricht wird erneut versucht.':'Ausgelost: '+(g.history.at(-1)?.names.join(', ')||'Keine Teilnehmer');}
 else if(sub==='reroll'){const g=await this.reroll(i.options.getInteger('gewinner'));text='Neuziehung: '+(g.history.at(-1)?.names.join(', ')||'Keine weiteren Teilnehmer');}
 else if(sub==='cancel'){const g=this.state.giveaway;if(!g||g.status!=='active')throw new Error('Kein aktives Giveaway.');g.status='cancelled';this.save();text='Giveaway abgebrochen.';}
 else if(sub==='overlay'){text='Private OBS-URL (nicht öffentlich teilen):\n'+this.publicUrl+'/stream/overlay/'+this.overlayKey;}
 }await i.editReply({content:text||'Erledigt.',allowedMentions:{parse:[]}});}catch(e){await i.editReply({content:'❌ '+clean(e.message,180)}).catch(()=>{});}return true;}
 error(e){this.lastError=clean(e.message,240);this.log.warn?.('[UNFUG Stream]',this.lastError.replace(/(access_token|refresh_token|client_secret)=\S+/gi,'$1=[REDACTED]'));}
 async start(){if(this.started)return;this.started=true;if(!this.guildId||!this.id||!this.secret||!this.publicUrl){this.log.warn('[UNFUG Stream] Konfiguration unvollständig; keine Verbindung gestartet.');return;}try{if(this.auth.access_token){await this.validateAuth();await this.resolveChannel();this.ready=true;this.openChat();}}catch(e){this.error(e);}this.timer=setInterval(()=>this.poll(),60000);this.timer.unref?.();this.giveawayTimer=setInterval(()=>this.tick().catch(e=>this.error(e)),5000);this.giveawayTimer.unref?.();this.validateTimer=setInterval(()=>this.validateAuth().catch(e=>this.error(e)),3600000);this.validateTimer.unref?.();this.watchdog=setInterval(()=>{if(this.ws&&this.sessionId&&this.now()-this.lastEventAt>this.keepaliveMs*2){this.error(new Error('Twitch EventSub Keepalive abgelaufen; neue Verbindung.'));this.openChat();}},15000);this.watchdog.unref?.();await this.poll();}
 async tick(){const g=this.state.giveaway;if(g?.status==='active'&&g.endsAt<=this.now())await this.endGiveaway();else if(g?.status==='drawing')await this.endGiveaway();else if(g?.pending)await this.publishResult();}
 close(){this.started=false;clearInterval(this.timer);clearInterval(this.giveawayTimer);clearInterval(this.validateTimer);clearInterval(this.watchdog);clearTimeout(this.reconnectTimer);this.ws?.close();this.db.close();}
 overlayData(){const g=this.state.giveaway;const visible=g&&!(g.status==='ended'&&this.now()-(g.displayAt||g.endedAt||0)>300000)&&g.status!=='cancelled';return {channel:this.channel,live:!!this.state.live,giveaway:visible?{prize:g.prize,status:g.status,endsAt:g.endsAt,participants:this.count(g),keyword:g.keyword,winners:g.history.at(-1)?.names||[]}:null};}
 async http(req,res){const u=new URL(req.url||'/', 'http://localhost');if(!u.pathname.startsWith('/stream/'))return false;if(req.method!=='GET'){this.respond(res,405,'Method not allowed');return true;}if(u.pathname==='/stream/oauth/callback'){await this.callback(req,res,u);return true;}const key=this.overlayKey;if(u.pathname==='/stream/overlay/'+key){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors *"});res.end(OVERLAY.replaceAll('__KEY__',key));return true;}if(u.pathname==='/stream/api/'+key){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end(JSON.stringify(this.overlayData()));return true;}this.respond(res,404,'Not found');return true;}
}
const OVERLAY=`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;background:transparent;color:#fff;font:600 24px Arial,sans-serif}#box{display:none;position:absolute;top:30px;left:50%;transform:translateX(-50%);width:min(720px,90vw);padding:24px 32px;background:#101015ee;border:1px solid #78748b;text-align:center;box-shadow:0 8px 35px #0008}small{font-size:12px;letter-spacing:5px;color:#aaa}h1{font-size:28px;margin:12px 0}#time{font-size:44px;color:#c1a4ff;margin:12px}#info{font-size:17px;color:#bbb}#winners{font-size:21px;color:#d4baff;margin-top:12px}</style><div id="box"><small>UNFUG / LIVE GIVEAWAY</small><h1 id="prize"></h1><div id="time"></div><div id="info"></div><div id="winners"></div></div><script>let state=null;const el=id=>document.getElementById(id);async function load(){try{const r=await fetch('/stream/api/__KEY__',{cache:'no-store'});if(r.ok)state=await r.json()}catch{}}function render(){const g=state?.giveaway;el('box').style.display=g?'block':'none';if(!g)return;el('prize').textContent=g.prize;el('info').textContent=g.participants+' Teilnehmer  •  '+g.keyword;el('time').textContent=g.status==='active'?(function(ms){let s=Math.ceil(Math.max(0,ms)/1000);return Math.floor(s/3600).toString().padStart(2,'0')+':'+Math.floor(s%3600/60).toString().padStart(2,'0')+':'+(s%60).toString().padStart(2,'0')})(g.endsAt-Date.now()):g.status==='ended'?'BEENDET':g.status==='cancelled'?'ABGEBROCHEN':'AUSLOSUNG';el('winners').textContent=g.winners.length?'Gewinner: '+g.winners.join(', '):''}load();setInterval(load,3000);setInterval(render,250);</script></html>`;
module.exports={StreamIntegration,commands:commands.map(c=>c.toJSON()),duration,draw};
