'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {EventEmitter}=require('node:events');
const {StreamIntegration,duration,draw}=require('../index');
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ufg-'));const sent=[];let time=1000000;const client={channels:{fetch:async()=>({isTextBased:()=>true,send:async p=>{sent.push(p);return{id:'123'};}})}};const m=new StreamIntegration({client,env:{DATA_DIR:dir,TWITCH_CHANNEL:'toomturboo',TWITCH_CLIENT_ID:'test',TWITCH_CLIENT_SECRET:'test',STREAM_GUILD_ID:'123456789012345678',PUBLIC_URL:'https://test.example'},now:()=>time,fetchFn:async()=>{throw Error('Network disabled')},logger:{warn(){}}});return{m,dir,sent,advance:n=>time+=n,close(){m.close();fs.rmSync(dir,{recursive:true,force:true});}};}
test('duration bounds and unbiased unique selection',()=>{assert.equal(duration('5m'),300000);assert.equal(duration('1d'),86400000);assert.equal(duration('0m'),0);assert.equal(duration('31d'),0);assert.equal(duration('bad'),0);assert.equal(new Set(draw(['a','a','b','c'],20)).size,3);});
test('Twitch IDs prevent duplicate entries and wrong keywords',()=>{const t=setup();try{const g=t.m.startGiveaway({prize:'Test',ms:60000});const e={chatter_user_id:'10',chatter_user_name:'Alice',message:{text:'!join'},message_id:'m1'};assert.equal(t.m.join(e),true);assert.equal(t.m.join(e),false);assert.equal(t.m.join({...e,message_id:'m2',chatter_user_name:'Changed'}),true);assert.equal(t.m.count(g),1);assert.equal(t.m.join({...e,message_id:'m3',message:{text:'!other'}}),false);t.advance(60000);assert.equal(t.m.join({...e,message_id:'m4'}),false);}finally{t.close();}});
test('persistent entries, secure draw, reroll excludes all previous winners',async()=>{const t=setup();try{const g=t.m.startGiveaway({prize:'Test',ms:60000,winners:2});for(let i=1;i<=5;i++)t.m.join({chatter_user_id:String(i),chatter_user_name:'User'+i,message_id:'m'+i,message:{text:'!join'}});t.m.auth={access_token:'TEST',refresh_token:'R',expiresAt:2000000};t.m.sendChat=async()=>{};const first=await t.m.endGiveaway();assert.equal(first.winnerIds.length,2);const second=await t.m.reroll(2);assert.equal(second.winnerIds.length,2);assert.equal(second.winnerIds.filter(x=>first.history[0].ids.includes(x)).length,0);assert.equal(t.m.count(g),5);const again=await t.m.reroll(2);assert.equal(again.winnerIds.length,1);assert.equal(new Set(again.history.flatMap(h=>h.ids)).size,5);}finally{t.close();}});
test('SQLite survives process recreation',()=>{const t=setup();try{const g=t.m.startGiveaway({prize:'Persist',ms:60000});t.m.join({chatter_user_id:'44',chatter_user_name:'Tester',message:{text:'!join'}});const other=new StreamIntegration({client:t.m.client,env:t.m.env,logger:{warn(){}}});assert.equal(other.count(g),1);assert.equal(other.state.giveaway.id,g.id);other.close();}finally{t.close();}});
test('unauthorized Discord command cannot mutate state',async()=>{const t=setup();try{let reply;const i={isChatInputCommand:()=>true,commandName:'streamgiveaway',inGuild:()=>true,guildId:'123456789012345678',guild:{ownerId:'owner'},user:{id:'stranger'},memberPermissions:{has:()=>false},reply:async p=>{reply=p;}};assert.equal(await t.m.handle(i),true);assert.match(reply.content,/Keine Berechtigung/);assert.equal(t.m.state.giveaway,undefined);}finally{t.close();}});
test('announcement is once per stream and test does not ping',async()=>{const t=setup();try{t.m.state.config={channelId:'123',enabled:true,roleId:'456',text:'Live {title} {url}'};const s={id:'session1',title:'FiveM'};await t.m.announce(s);assert.equal(t.sent.length,1);await t.m.announce(s);assert.equal(t.sent.length,1);await t.m.announce(s,{test:true});assert.equal(t.sent.length,2);assert.deepEqual(t.sent[1].allowedMentions.roles,[]);assert.equal(t.m.state.announcedId,'session1');}finally{t.close();}});
test('OAuth state expires and rejects missing authorization code',async()=>{const t=setup();try{const url=await t.m.connectUrl('owner');const state=new URL(url).searchParams.get('state');let status;await t.m.callback(null,{writeHead:s=>{status=s},end(){}},new URL('https://test.example/stream/oauth/callback?state='+state));assert.equal(status,400);assert.equal(t.m.pending.size,0);}finally{t.close();}});
test('read-only overlay API hides secrets and rejects other paths',async()=>{const t=setup();try{const call=async url=>{let status,body='';await t.m.http({method:'GET',url},{writeHead(s){status=s},end(s){body=s||''}});return{status,body};};const r=await call('/stream/api/'+t.m.overlayKey);assert.equal(r.status,200);assert.equal(r.body.includes('test.example'),false);assert.equal(r.body.includes('access_token'),false);assert.equal((await call('/stream/api/wrong')).status,404);let status;await t.m.http({method:'POST',url:'/stream/api/'+t.m.overlayKey},{writeHead:s=>{status=s},end(){}});assert.equal(status,405);}finally{t.close();}});
test('OAuth refresh persists rotated token without exposing it in overlay',async()=>{const t=setup();try{t.m.auth={access_token:'OLD',refresh_token:'REFRESH',expiresAt:1};t.m.put('auth',t.m.auth);let calls=0;t.m.fetch=async(url,opts)=>{calls++;assert.match(url,/oauth2\/token/);assert.match(opts.body.toString(),/grant_type=refresh_token/);return {ok:true,text:async()=>JSON.stringify({access_token:'NEW',refresh_token:'NEW_REFRESH',expires_in:3600})};};assert.equal(await t.m.userAuth(),'NEW');assert.equal(t.m.get('auth',{}).refresh_token,'NEW_REFRESH');assert.equal(calls,1);assert.equal(JSON.stringify(t.m.overlayData()).includes('NEW_REFRESH'),false);}finally{t.close();}});
test('EventSub welcome subscribes to broadcaster chat using authorized user',async()=>{const t=setup();try{t.m.auth={access_token:'USER',refresh_token:'R',expiresAt:2000000,userId:'123'};t.m.channelId='123';let route,opts;t.m.helix=async(r,o)=>{route=r;opts=o;return {data:[]};};await t.m.onEvent({metadata:{message_type:'session_welcome'},payload:{session:{id:'session',keepalive_timeout_seconds:30}}});assert.equal(route,'/eventsub/subscriptions');assert.equal(opts.user,true);assert.deepEqual(opts.body.condition,{broadcaster_user_id:'123',user_id:'123'});assert.equal(opts.body.type,'channel.chat.message');}finally{t.close();}});
test('failed result publication preserves winner and prevents a second giveaway',async()=>{const t=setup();try{const g=t.m.startGiveaway({prize:'Test',ms:60000});t.m.join({chatter_user_id:'1',chatter_user_name:'Alice',message:{text:'!join'}});t.m.auth={access_token:'TEST',refresh_token:'R',expiresAt:2000000};t.m.sendChat=async()=>{throw Error('Temporary chat failure');};await assert.rejects(t.m.endGiveaway(),/Temporary chat failure/);assert.equal(g.status,'ended');assert.equal(g.history.length,1);assert.ok(g.pending);assert.throws(()=>t.m.startGiveaway({prize:'Next',ms:60000}),/vorherige/);let sent=0;t.m.sendChat=async()=>{sent++;};await t.m.publishResult();assert.equal(sent,1);assert.equal(g.pending,null);assert.equal(g.history.length,1);}finally{t.close();}});
test('live announcement retries after a failed send and never pings on a test',async()=>{const t=setup();try{t.m.state.config={channelId:'123',enabled:true,roleId:'456'};let fail=true;t.m.client.channels.fetch=async()=>({id:'123',isTextBased:()=>true,messages:{fetch:async()=>new Map()},send:async p=>{if(fail)throw Error('Discord unavailable');t.sent.push(p);return{id:'message'};}});const s={id:'session',title:'FiveM'};await assert.rejects(t.m.announce(s),/Discord unavailable/);assert.equal(t.m.state.announcedId,null);fail=false;await t.m.announce(s);assert.equal(t.sent.length,1);assert.equal(t.sent[0].allowedMentions.roles[0],'456');await t.m.announce(s,{test:true});assert.deepEqual(t.sent[1].allowedMentions.roles,[]);}finally{t.close();}});
